const allData = [
  [`Recent Repositories`, `最近仓库`],
  [`Search or jump to…`, `搜索并跳转至...`],
  [`Issues`, `问题`],
  [`Pull`, `合并`],
  [`request`, `请求`],
  [`s`, ``],
  [`Marketplace`, `市场`],
  [`Explore`, `探索`],
  [`Following`, `关注者`],
  [`Find a repository…`, `查找仓库`],
  [`Latest changes`, `最新变化`],
  [`hours ago`, `小时前`],
  [`days ago`, `天前`],
  [`New`, `新建`],
  [`Explore repositories`, `探索存储库`],
  [`Explore more →`, `探索更多 →`],
  [`Set status`, `设置状态`],
  [`Your profile`, `个人信息`],
  [`Your repositories`, `个人仓库`],
  [`Your codespaces`, `你的 codespaces`],
  [`Your projects`, `你的项目`],
  [`Signed in as`, `登陆账户为`],
  [`Feature preview`, `功能预览`],
  [`Upgrade`, `升级`],
  [`Try Enterprise`, `尝试企业版`],
  [`Help`, `帮助`],
  [`Settings`, `设置`],
  [`Sign out`, `退出`],
  [`Overview`, `概述`],
  [`Repositories`, `仓库`],
  [`Projects`, `项目`],
  [`Packages`, `包`],
  [`Popular repositories`, `流行的仓库`],
  [`Edit profile`, `编辑个人信息`],
  [`followers`, ` 被关注`],
  [`following`, ` 关注`],
  [`Public`, `公开`],
  [`Customize your pins`, `定义你的置顶项目`],
  [`Contribution settings`, `贡献设置`],
  [`Pinned`, `置顶`],
  [`Learn how we count contributions`, `了解我们如何计算贡献`],
  [`Code review`, `代码评审`],
  [`Pull requests`, `合并请求`],
  [`Commits`, `提交`],
  [`Contribution activity`, `贡献活动`],
  [`Show more activity`, `显示更多活动`],
  [`Code`, `代码`],
  [`Go to file`, `转至文件`],
  [`Add file`, `添加文件`],
  [`About`, `关于`],
  [`Pin`, `置顶`],
  [`Pin this repository to your profile`, `置顶这个项目到你的个人信息`],
  [`New repository`, `新建仓库`],
  [`Import repository`, `导入仓库`],
  [`New organization`, `新建组织`],
  [`Create a new release`, `创建一个新的版本`],
  [`Publish your first package`, `发布你的第一个包`],
  [`Releases`, `发布`],
  [`Packages `, `包`],
  [`No packages published`, `没有发布任何软件包`],
  [`Languages`, `语言`],
  [`Show more`, `显示更多`],
  [`Recent activity`, `最新动态`],
  [
    `When you take actions across GitHub, we’ll provide links to that activity here.`,
    `当你在 GitHub 上采取行动时，我们会在这里提供该活动的链接。`,
  ],
  [`More`, `更多`],
  [`Subscribe to your news feed`, `订阅你的 feed`],
  [`Blog`, `博客`],
  [`Shop`, `商店`],
  [`Contact GitHub`, `联系 Github`],
  [`Pricing`, `定价`],
  [`Training`, `培训`],
  [`Status`, `状态`],
  [`Security`, `安全`],
  [`Terms`, `服务条款`],
  [`Privacy`, `隐私`],
  [`Docs`, `文档`],
  [`New project`, `新建项目`],
  [`Activity  overview`, `活动概览`],
  [`Projects`, `项目`],
  [`Security`, `安全`],
  [`Insights`, `统计`],
  [`Create new file`, `创建新的文件`],
  [`Upload files`, `上传文件`],
  [`Code`, `代码`],
  [`Local`, `本地`],
  [`Clone`, `克隆`],
  [`Open with GitHub Desktop`, `在 Github 桌面程序中打开`],
  [`Download ZIP`, `下载压缩包`],
  [`New codespace`, `新建 codespace`],
  [`Less`, `更少`],
  [`Select type`, `选择类型`],
  [`Type`, `类型`],
  [`Language`, `语言`],
  [`Sort`, `排序`],
  [`Private`, `私有`],
  [`Select language`, `选择语言`],
  [`Select order`, `选择顺序`],
  [`Last updated`, `最近更新`],
  [`Create a new repository`, `创建一个新的仓库`],
  [`Owner`, `拥有者`],
  [`Repository name`, `仓库名字`],
  [`Description`, `描述`],
  [`(optional)`, `(可选)`],
  [
    `Anyone on the internet can see this repository. You choose who can commit.`,
    `互联网上的任何人都可以看到这个存储库。你选择谁能够提交。`,
  ],
  [
    `You choose who can see and commit to this repository.`,
    `你可以选择谁可以看到和提交这个版本库。`,
  ],
  [
    `A repository contains all project files, including the revision history. Already have a project repository elsewhere?`,
    `一个仓库包含所有项目文件，包括修订历史。在其他地方已经有一个项目库了？`,
  ],
  [`Import a repository.`, `导入仓库`],
  [
    `Skip this step if you’re importing an existing repository.`,
    `如果你要导入一个已有的版本库，请跳过这一步。`,
  ],
  [
    `Choose which files not to track from a list of templates.`,
    `从一个模板列表中选择哪些文件不需要跟踪。`,
  ],
  [
    `This is where you can write a long description for your project.`,
    `在这里，你可以为你的项目写一个长的描述。`,
  ],
  [
    `A license tells others what they can and can't do with your code.`,
    `许可证告诉别人他们可以和不可以用你的代码做什么。`,
  ],
  [
    `You are creating a public repository in your personal account.`,
    `你正在你的个人账户中创建一个公共库。`,
  ],
  [`Initialize this repository with:`, `用以下方式初始化这个存储库：`],
  [`Create repository`, `创建仓库`],
  [
    `Great repository names are short and memorable. Need inspiration? How about`,
    `伟大的仓库名称是简短而令人难忘的。需要灵感吗？比如 `,
  ],
  [`Your personal account`, `你的个人账户`],
  [`Public profile`, `公开资料`],
  [`Name`, `名字`],
  [`Change username`, `修改用户名`],
  [`Account`, `账户`],
  [`Export account data`, `导出账户数据`],
  [`Appearance`, `外观`],
  [`Accessibility`, `无障碍设施`],
  [`Notifications`, `通知`],
  [`Access`, `访问`],
  [`Personal billing`, `个人帐单`],
  [`Emails`, `邮件`],
  [`Billing and plans`, `账单和计划`],
  [
    `This is a list of SSH keys associated with your account. Remove any keys that you do not recognize.`,
    `这是与你的账户相关的 SSH 密钥的列表，删除任何你不认识的密钥`,
  ],
  [`Organizations`, `组织`],
  [`You are not a member of any organizations.`, `你不是任何组织的成员  `],
  [`Archives`, `归档`],
  [`Security log`, `安全日志`],
  [`Sponsorship log`, `赞助日志`],
  [`No sponsorship activity in this time period`, `这段时间内没有赞助活动`],
  [`Sign in to GitHub`, `登录到 Github`],
  [`Username or email address`, `用户名或邮箱`],
  [`Password`, `密码`],
  [`Sign in`, `登录`],
  [`New to GitHub?`, `刚来 Github？`],
  [`Create an account`, `创建一个账户`],
  [`Forgot password?`, `忘记密码？`],
  [`Create an account`, ``],
  [
    `Label issues and pull requests for new contributors`,
    `为新的贡献者标记问题和合并请求`,
  ],
  [`Filters`, `过滤`],
  [`New Issue`, `新问题`],
  [`There aren’t any open issues.`, `没有任何公开的问题。`],
  [`Signing in…`, `登录中...`],
  [`Edit repository details`, `编辑仓库详情信息`],
  [`Website`, `网站`],
  [`Cancer`, `取消`],
  [`Save changes`, `保存修改`],
  [`Protect this branch`, `保护这个分支`],
  [`Get started with GitHub Actions`, `开始使用 Github Actions`],
  [
    `Build, test, and deploy your code. Make code reviews, branch management, and issue triaging work the way you want. Select a workflow to get started.`,
    `构建、测试和部署你的代码。使代码审查、分支管理和问题分流以你想要的方式进行。选择一个工作流程来开始。`,
  ],
  [`Browse all categories`, `浏览所有类型`],
  [`Automation`, `自动化`],
  [`Deployment`, `部署`],
  [`Continuous integration`, `持续集成`],
  [`Reporting`, `报告`],
  [`General`, `常规`],
  [`Public email`, `公开的邮箱`],
  [`Bio`, `个人简历`],
  [`URL`, `网站`],
  [`Twitter username`, `Twitter 用户名`],
  [`Company`, `公司`],
  [`Location`, `地址`],
  [`Contributions & Activity`, `贡献和活动`],
  [`Successor settings`, `继承人设置`],
  [`You have not designated a successor.`, `你还没有指定继承人`],
  [`Delete account`, `删除账户`],
  [
    `Once you delete your account, there is no going back. Please be certain.`,
    `一旦你删除了你的账户，就不能够找回了，请慎重`,
  ],
  [`Display current local time`, `显示当前的本地时间`],
  [`Keyboard shortcuts`, `快捷键`],
  [`Subscriptions`, `订阅`],
  [`Verified domains`, `验证的域名`],
  [`There are no verified domains.`, `没有经过验证的域名`],
  [`Password and authentication`, `密码和身份验证`],
  [`Change password`, `修改密码`],
  [`Old password`, `旧密码`],
  [`New password`, `新密码`],
  [`Confirm new password`, `确认新的密码`],
  [`Two-factor authentication`, `两步验证`],
  [`Confirm new password`, `确认新的密码`],
  [`Confirm access`, `确认访问`],
  [`Confirm`, `确认`],
  [`Who has access`, `谁有权限`],
  [`Code and automation`, `代码和自动化`],
  [`Default branch`, `默认分支`],
  [`Branch protection rules`, `分支保护规则`],
  [`Protected tags`, `保护标签`],
  [`Environments`, `环境变量`],
  [`Code security and analysis`, `代码安全性和分析`],
  [`Integrations`, `集成`],
  [`Email notifications`, `邮件通知`],
  [`Collaborators`, `合作者`],
  [`Contributors`, `贡献者`],
  [`Community Standards`, `社区标准`],
  [`Traffic`, `流量`],
  [`Code frequency`, `代码频率`],
  [`Dependency graph`, `依赖图`],
  [`Contributors`, `贡献者`],
  [`You can`, `你可以`],
  [`@mention`, `@`],
  [
    `other users and organizations to link to them.`,
    `其他用户和组织来链接它们`,
  ],
  [`Save`, `保存`],
  [`Cancel`, `取消`],
  [`Welcome to the all-new projects`, `欢迎来到全新的项目`],
  [`No open projects`, `没有开放的项目`],
  [`Add a bio`, `添加个人简介`],
  [`Loading more...`, `正在加载中`],
  [
    `Your popular repositories will now be shown instead of your pins.`,
    `你的热门仓库现在将显示，而不是你的置顶`,
  ],
  [`Unpin`, `不置顶`],
  [`Your pins have been updated.`, `你的置顶已经更新了`],
  [`Advanced search`, `高级搜索`],
  [`Branches`, `分支`],
  [`Social Preview`, `社交预览`],
  [
    `Upload an image to customize your repository’s social media preview.`,
    `上传图片来定制你仓库的社交媒体预览`,
  ],
  [`Pull Requests`, `合并请求`],
  [`Danger Zone`, `危险区`],
  [`Change repository visibility`, `修改仓库的可见性`],
  [`Transfer ownership`, `转让所有权`],
  [`This repository is currently public.`, `这个仓库当前是公开的`],
  [`Archive this repository`, `归档这个仓库`],
  [
    `Mark this repository as archived and read-only.`,
    `将此版本库标记为归档和只读`,
  ],
  [`Delete this repository`, `删除这个仓库`],
  [
    `Once you delete a repository, there is no going back. Please be certain.`,
    `一旦你删除了这个仓库，就不能够撤回了，请确认`,
  ],
  [`Are you absolutely sure?`, `你真的确定吗？`],
  [`Change visibility`, `修改可见性`],
  [`Change to private`, `修改为私有`],
  [`Transfer`, `转移`],
  [`Edit status`, `编辑状态`],
  [`Busy`, `忙`],
  [`Clear status`, `清除状态`],
  [`Never`, `从不`],
  [`Your main branch isn't protected`, `你的 main 分支不是受保护的`],
  [
    `Protect this branch from force pushing or deletion, or require status checks before merging.`,
    `保护这个分支不被强行推送或删减，或要求在合并前进行状态检查 `,
  ],
  [`Learn more`, `学习更多`],
  [`Branch protection rule`, `分支保护规则`],
  [`Protect your most important branches`, `保护你最重要的分支`],
  [`Achievements`, `成就`],
  [`Send feedback`, `发送反馈`],
  [`Choose a license`, `选择许可证`],
  [`Learn more.`, `学习更多`],
  [`Import your project to GitHub`, `导入你得项目到 Github`],
  [`Inbox`, `收件箱`],
  [`Prev`, `上页`],
  [`Next`, `下页`],
  [`Saved`, `保存`],
  [`Done`, `完成`],
  [`Manage notifications`, `管理通知`],
  [`See more`, `查看更多`],
  [`Include in the home page`, `显示在页面上`],
  [`Discussions`, `讨论`],
  [`Users`, `用户`],
  [`This repository is currently private.`, `这个仓库当前是私有的`],
  [`Lists`, `列表`],
  [`Create list`, `创建列表`],
  [`Pushes`, `推送`],
  [
    `Limit how many branches and tags can be updated in a single push`,
    `限制一次推送中可以更新多少个分支和标签`,
  ],
  [`I want to make this repository private`, `我想要让这个仓库变为私有`],
  [`I have read and understand these effects`, `我已经阅读并理解了这些影响`],
  [`New issue`, `新建问题`],
  [`Labels`, `标签`],
  [`New milestone`, `新建里程碑`],
  [`Milestones`, `里程碑`],
  [`You haven’t created any Milestones.`, `你还没有创建任何里程碑。`],
  [`Edit`, `编辑`],
  [`Delete`, `删除`],
  [`Close`, `关闭`],
  [`Success`, `完成`],
  [`Dashboard`, `仪表盘`],
  [`to search`, `搜索`],
  [`Create your first project`, `创建您的第一个项目`],
  [
  `Ready to start building? Create a repository for a new idea or bring over an existing repository to keep contributing to it.`,
  `准备好开始构建了吗？为新的想法创建一个存储库，或导入一个存储库以继续为它做出贡献。`,
  ],
  [`Filter`, `筛选`],
  [`Events`, `活动`],
  [`Activity you want to see on your feed`, `您希望在推送中看到的活动`],
  [`Stars`, `星`],
  [`main`, `主干`],
  [`Default`, `默认值`],
  [`Tags`, `标签`],
  [`Watch`, `查看`],
  [`Fork`, `复刻`],
  [`Starred`, `标星`],
  [`Switch branches/tags`, `查看所有分支/标签`],
  [`Profile picture`, `简介图片`],
  [`SSH and GPG keys`, `SSH和GPG密钥`],
  [`Cancel changes`, `取消更改`],
  [`Commit changes...`, `提交更改...`],
  [`Agents`, `智能体`],
  [`Actions`, `工作流`],
  [`Security and quality`, `安全与质量`],
  [`This branch is`, `此分支`],
  [`Contribute`, `贡献`],
  [`Sync fork`, `同步复刻`],
  [`forked from`, `复刻自`],
  [`No releases published`, `未发布任何版本`],
  [`Readme`, `自述文件`],
  [`Activity`, `动态`],
  [`Star`, `标星`],
  [`up to date with`, `已同步于`],
  [`Report repository`, `举报此仓库`],
  [`Latest`, `最新`],
  [`Community`, `社区`],
  [`Contact`, `联系`],
  [`Manage cookies`, `管理 Cookie`],
  [`Do not share my personal information`, `请勿共享我的个人信息`],
  [`Participating and @mentions`, `参与和 @提及`],
  [`Only receive notifications from this repository when participating or @mentioned.`, `仅在参与或被 @提及 时接收此仓库的通知。`],
  [`All Activity`, `所有活动`],
  [`Notified of all notifications on this repository.`, `接收此仓库的所有通知。`],
  [`Ignore`, `忽略`],
  [`Never be notified.`, `从不接收通知。`],
  [`Custom`, `自定义`],
  [`Select events you want to be notified of in addition to participating and @mentions.`, `选择除了参与和 @提及 之外，您还希望接收通知的事件。`],
  [`Switch repository`, `切换仓库`],
  [`Search repositories`, `搜索仓库`],
  [`Home`, `主页`],
  [`All issues`, `所有问题`],
  [`All pull requests`, `所有合并请求`],
  [`All repositories`, `所有仓库`],
  [`MCP registry`, `MCP 注册中心`],
  [`Top repositories`, `热门仓库`],
  [`Search for repositories`, `搜索仓库`],
  [`Blame`, `追溯`],
  [`code`, `代码`],
  [`Files`, `文件`],
  [`files`, `文件`],
  [`File`, `文件`],
  [`file`, `文件`],
  [`Congratulations, you're all set!`, `恭喜，您已全部设置完毕！`],
  [`Your device is now connected.`, `您的设备现已连接。`],
  [`Watchers`, `关注者`],
  [`Forks`, `复刻`],
  [`stars`, ` 颗星`],
  [`watching`, ` 人关注`],
  [`forks`, ` 次复刻`],
  [`fork`, ` 次复刻`],
  [`star`, ` 颗星`],
  [`README`, `自述文件`],
  [`License`, `许可证`],
  [`LICENSE`, `许可证`],
  [`license`, `许可证`],
  [`No contributors`, `没有贡献者`],
  [`Suggested workflows`, `推荐工作流`],
  [`Based on your tech stack`, `基于您的技术栈`],
  [`Datadog Synthetics logo`, `Datadog Synthetics 图标`],
  [`Run Datadog Synthetic tests within your GitHub Actions workflow`, `在您的 GitHub Actions 工作流中运行 Datadog 合成测试`],
  [`Publish Node.js Package logo`, `发布 Node.js 包图标`],
  [`Publish Node.js Package`, `发布 Node.js 包`],
  [`Publishes a Node.js package to npm.`, `将 Node.js 包发布到 npm。`],
  [`Webpack logo`, `Webpack 图标`],
  [`Build a NodeJS project with npm and webpack.`, `使用 npm 和 webpack 构建 NodeJS 项目。`],
  [`More workflows`, `更多工作流`],
  // Dismiss/Configure suggestions
  [`Dismiss suggestions`, `忽略推荐`],
  [`Configure`, `配置`],
  [`configure`, `配置`],
  [`configur`, `配置`],
  [`Skip this and set up a workflow yourself`, `跳过此步骤并自行创建工作流`],
  [`Search workflows`, `搜索工作流`],
  [`Suggested for this repository`, `为此仓库推荐`],
  [`Publish Node.js Package to GitHub Packages`, `将 Node.js 包发布到 GitHub Packages`],
  [`By GitHub Actions`, `由 GitHub Actions 提供`],
  [`Publish Node.js Package to GitHub Packages logo`, `将 Node.js 包发布到 GitHub Packages 图标`],
  [`Publishes a Node.js package to GitHub Packages.`, `将 Node.js 包发布到 GitHub Packages。`],
  [`Deno logo`, `Deno 图标`],
  [`Test your Deno project`, `测试您的 Deno 项目`],
  [`View all`, `查看全部`],
  [`Deploy Node.js to Azure Web App`, `将 Node.js 部署到 Azure Web App`],
  [`By Microsoft Azure`, `由 Microsoft Azure 提供`],
  [`Deploy Node.js to Azure Web App logo`, `将 Node.js 部署到 Azure Web App 图标`],
  [`Build a Node.js project and deploy it to an Azure Web App.`, `构建 Node.js 项目并将其部署到 Azure Web App。`],
  [`Deploy Node.js to Azure Functions App`, `将 Node.js 部署到 Azure Functions App`],
  [`Deploy Node.js to Azure Functions App logo`, `将 Node.js 部署到 Azure Functions App 图标`],
  [`Build a Node.js project and deploy it to an Azure Functions App on Windows or Linux.`, `构建 Node.js 项目并将其部署到 Windows 或 Linux 上的 Azure Functions App。`],
  [`Deploy to Amazon ECS`, `部署到 Amazon ECS`],
  [`By Amazon Web Services`, `由 Amazon Web Services 提供`],
  [`Deploy to Amazon ECS logo`, `部署到 Amazon ECS 图标`],
  [`Deploy a container to an Amazon ECS service powered by AWS Fargate or Amazon EC2.`, `将容器部署到由 AWS Fargate 或 Amazon EC2 支持的 Amazon ECS 服务中。`],
  [`Build and Deploy to GKE`, `构建并部署到 GKE`],
  [`By Google Cloud`, `由 Google Cloud 提供`],
  [`Build and Deploy to GKE logo`, `构建并部署到 GKE 图标`],
  [`Build a docker container, publish it to Google Container Registry, and deploy to GKE.`, `构建 Docker 容器，将其发布到 Google Container Registry，然后部署到 GKE。`],
  [`By HashiCorp`, `由 HashiCorp 提供`],
  [`Terraform logo`, `Terraform 图标`],
  [`Set up Terraform CLI in your GitHub Actions workflow.`, `在您的 GitHub Actions 工作流中设置 Terraform CLI。`],
  [`Deploy to Alibaba Cloud ACK`, `部署到阿里云 ACK`],
  [`By Alibaba Cloud`, `由阿里云提供`],
  [`Deploy to Alibaba Cloud ACK logo`, `部署到阿里云 ACK 图标`],
  [`Deploy a container to Alibaba Cloud Container Service for Kubernetes (ACK).`, `将容器部署到阿里云容器服务 Kubernetes 版 (ACK)。`],
  [`Deploy to IBM Cloud Kubernetes Service`, `部署到 IBM Cloud Kubernetes Service`],
  [`By IBM`, `由 IBM 提供`],
  [`Deploy to IBM Cloud Kubernetes Service logo`, `部署到 IBM Cloud Kubernetes Service 图标`],
  [`Build a docker container, publish it to IBM Cloud Container Registry, and deploy to IBM Cloud Kubernetes Service.`, `构建 Docker 容器，将其发布到 IBM Cloud Container Registry，然后部署到 IBM Cloud Kubernetes Service。`],
  [`By Tencent Cloud`, `由腾讯云提供`],
  [`Tencent Kubernetes Engine logo`, `Tencent Kubernetes Engine 图标`],
  [`This workflow will build a docker container, publish and deploy it to Tencent Kubernetes Engine (TKE).`, `此工作流将构建 Docker 容器，并将其发布和部署到腾讯云容器服务 (TKE)。`],
  [`CodeQL Analysis`, `CodeQL 分析`],
  [`By GitHub`, `由 GitHub 提供`],
  [`Security analysis from GitHub for C, C++, C#, Go, Java, JavaScript, TypeScript, Python, Ruby, Kotlin and Swift developers.`, `GitHub 为 C、C++、C#、Go、Java、JavaScript、TypeScript、Python、Ruby、Kotlin 和 Swift 开发者提供的安全分析。`],
  [`Code scanning`, `代码扫描`],
  [`Dependency Review`, `依赖项审查`],
  [`Scans Pull Requests on each push for the introduction and/or resolution of vulnerable dependencies to the repository`, `在每次推送时扫描合并请求（Pull Request），以检查是否引入或解决有漏洞的依赖项`],
  [`Dependency review`, `依赖项审查`],
  [`APIsec Scan`, `APIsec 扫描`],
  [`By APIsec`, `由 APIsec 提供`],
  [`APIsec Scan logo`, `APIsec 扫描图标`],
  [
    `APIsec provides the industry’s only automated and continuous API testing platform that uncovers security vulnerabilities and logic flaws in APIs.`,
    `APIsec 提供了业界唯一的自动化和持续 API测试平台，可揭示 API 中的安全漏洞和逻辑缺陷。`
  ],
  [`By Appknox`, `由 Appknox 提供`],
  [`Appknox logo`, `Appknox 图标`],
  [
    `Use Appknox action for faster and precise security assessments of your iOS and Android apps developed using any programming language`,
    `使用 Appknox Action，对使用任何编程语言开发的 iOS 和 Android 应用进行更快、更精确的安全评估`
  ],
  [`SLSA Generic generator`, `SLSA 通用生成器`],
  [`By Open Source Security Foundation (OpenSSF)`, `由开源安全基金会 (OpenSSF) 提供`],
  [`SLSA Generic generator logo`, `SLSA 通用生成器图标`],
  [`Generate SLSA3 provenance for your existing release workflows`, `为您现有的发布工作流生成 SLSA3 来源凭证`],
  [`Build and test a Node.js project with npm.`, `使用 npm 构建并测试 Node.js 项目。`],
  [`SLSA Go releaser`, `SLSA Go 发布器`],
  [`SLSA Go releaser logo`, `SLSA Go 发布器图标`],
  [`Compile your Go project using a SLSA3 compliant builder`, `使用符合 SLSA3 规范的构建器编译您的 Go 项目`],
  [`Manual workflow`, `手动触发工作流`],
  [`Simple workflow that is manually triggered.`, `手动触发的简单工作流。`],
  [`Stale`, `清理过期问题`],
  [`Checks for stale issues and pull requests`, `检查过期的 Issue（问题）和 Pull Request（合并请求）`],
  [`AI issue summary`, `AI 问题总结`],
  [`Summarizes new issues`, `总结新提出的问题`],
  [`Greetings`, `欢迎寄语`],
  [`Greets users who are first time contributors to the repo`, `向首次为仓库做出贡献的用户发送欢迎寄语`],
  [`Static HTML`, `静态 HTML`],
  [`Static HTML logo`, `静态 HTML 图标`],
  [`Deploy static files in a repository without a build.`, `在不进行构建的情况下，将仓库中的静态文件进行部署。`],
  [`NuxtJS logo`, `NuxtJS 图标`],
  [`Package a NuxtJS site.`, `打包 NuxtJS 网站。`],
  [`Jekyll logo`, `Jekyll 图标`],
  [`Package a Jekyll site.`, `打包 Jekyll 网站。`],
  [`Next.js logo`, `Next.js 图标`],
  [`Package a Next.js site.`, `打包 Next.js 网站。`],
  [`Learn more about GitHub Actions`, `了解更多关于 GitHub Actions 的信息`],
  [`Getting started and core concepts`, `入门指南与核心概念`],
  [`New to Actions? Start here. Learn the core concepts and how to get started.`, `刚接触 Actions？从这里开始。了解核心概念并开启您的第一步。`],
  [`Configuring and managing workflows`, `配置与管理工作流`],
  [`Create custom workflows to control your project's life cycle processes.`, `创建自定义工作流以控制您的项目生命周期流程。`],
  [`Any language`, `任意语言`],
  [`Language and framework guides`, `语言与框架指南`],
  [`Guides for projects written in many programming languages.`, `针对使用多种编程语言编写的项目的指南。`],
  [`Welcome to Projects`, `欢迎使用项目 (Projects)`],
  [`Built to be flexible and adaptable, Projects gives you a live canvas to filter, sort, and group issues and pull requests in a table, board, or roadmap. Tailor them to your needs with custom fields, saved views, workflows, and insights.`, `项目 (Projects) 具备高度的灵活性和适应性，为您提供了一个实时画布，可在表格、看板或路线图中筛选、排序和分组 Issue（问题）及 Pull Request（合并请求）。通过自定义字段、保存的视图、工作流和洞察分析，量身定制符合您需求的项目。`],
  [`No sessions match your filters`, `没有符合您筛选条件的会话`],
  [`Try adjusting your search or filters.`, `请尝试调整您的搜索或筛选条件。`],
  [`Copilot uses AI. Check for mistakes.`, `Copilot 使用 AI。请注意检查错误。`],
  [`Template repository`, `模板仓库`],
  [`Template repositories let users generate new repositories with the same directory structure and files. Learn more about template repositories.`, `模板仓库允许用户生成具有相同目录结构和文件的新仓库。了解更多关于模板仓库的信息。`],
  [`The default branch is considered the “base” branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.`, `默认分支被视为您仓库中的“基础”分支，除非您指定其他分支，否则所有合并请求和代码提交都会自动针对该分支进行。`],
  [`Enable release immutability`, `启用发布不可变性`],
  [`Disallow assets and tags from being modified once a release is published.`, `发布后禁止修改资产和标签。`],
  [`Social preview`, `社交媒体预览`],
  [`Images should be at least 640×320px (1280×640px for best display).`, `图片尺寸应至少为 640×320 像素（推荐 1280×640 像素以达到最佳显示效果）。`],
  [`Download template`, `下载模板`],
  [`Wikis host documentation for your repository.`, `Wiki 用于托管您仓库的文档。`],
  [`Restrict editing to collaborators only`, `仅限制协作者编辑`],
  [`Public wikis will still be readable by everyone.`, `公开的 Wiki 仍可被所有人阅读。`],
  [`Issues integrate lightweight task tracking into your repository. Keep projects on track with issue labels and milestones, and reference them in commit messages.`, `Issue 将轻量级的任务跟踪集成到您的仓库中。通过 Issue 标签和里程碑保持项目处于正轨，并在提交信息中引用它们。`],
  [`Sponsorships help your community know how to financially support this repository.`, `赞助计划可帮助您的社区了解如何为该仓库提供资金支持。`],
  [`Display a "Sponsor" button`, `显示“赞助”按钮`],
  [`Add links to GitHub Sponsors or third-party methods your repository accepts for financial contributions to your project.`, `添加指向 GitHub Sponsors 或您仓库接受的其他第三方赞助方式的链接，以便为您的项目提供资金贡献。`],
  [`Preserve this repository`, `保留此仓库`],
  [`Include this code in the GitHub Archive Program.`, `将此代码纳入 GitHub 归档计划。`],
  [`Discussions is the space for your community to have conversations, ask questions and post answers without opening issues.`, `讨论区（Discussions）是您的社区进行对话、提出问题和发布解答的空间，而无需创建 Issue。`],
  [`Get started with Discussions`, `开启讨论区`],
  [`Engage your community by having discussions right in your repository, where your community already lives`, `在您的仓库（即您社区的聚集地）中直接进行讨论，从而增进社区互动。`],
  [`Projects on GitHub are created at the repository owner's level (organization or user) and can be linked to a repository's Projects tab. Projects are suitable for cross-repository development efforts such as feature work, complex product roadmaps or even Issue triage.`, `GitHub 上的项目是在仓库所有者级别（组织或用户）创建的，并可以链接 to 仓库的“项目”选项卡。项目适用于跨仓库的开发工作，例如功能开发、复杂的产品路线图甚至 Issue 分流分类。`],
  [`Pull requests allow others to suggest changes to your repository.`, `合并请求允许其他人向您的仓库建议更改。`],
  [`Pull request permissions`, `合并请求权限`],
  [`If restricted, pull requests will still be readable by everyone who can see this repository.`, `如果受到限制，合并请求仍可被所有能看到该仓库的人阅读。`],
  [`When merging pull requests, you can allow any combination of merge commits, squashing, or rebasing. At least one option must be enabled. If you have linear history requirement enabled on any protected branch, you must enable squashing or rebasing.`, `在合并合并请求时，您可以允许合并提交、壁挂合并（squash）或变基（rebase）的任意组合。必须至少启用一个选项。如果您在任何受保护分支上启用了线性历史记录要求，则必须启用壁挂合并或变基。`],
  [`Add all commits from the head branch to the base branch with a merge commit.`, `使用合并提交将头部分支中的所有提交添加到基础分支。`],
  [`Default commit message`, `默认提交信息`],
  [`Presented when merging a pull request with merge.`, `使用普通合并（merge）方式合并合并请求时显示。`],
  [`Allow squash merging`, `允许壁挂合并 (Squash)`],
  [`Combine all commits from the head branch into a single commit in the base branch.`, `将头部分支中的所有提交合并为基础分支中的单个提交。`],
  [`Presented when merging a pull request with squash.`, `使用壁挂合并（squash）方式合并合并请求时显示。`],
  [`Allow rebase merging`, `允许变基合并 (Rebase)`],
  [`Add all commits from the head branch onto the base branch individually.`, `将头部分支中的所有提交逐个添加到基础分支。`],
  [`Control how and when users are prompted to update their branches if there are new changes available in the base branch.`, `控制当基础分支有新更改可用时，如何以及何时提示用户更新其分支。`],
  [`Always suggest updating pull request branches`, `始终建议更新合并请求分支`],
  [`Whenever there are new changes available in the base branch, present an “update branch” option in the pull request.`, `只要基础分支有新更改，就在合并请求中显示“更新分支”选项。`],
  [`You can allow setting pull requests to merge automatically once all required reviews and status checks have passed.`, `您可以允许在所有要求的审查和状态检查通过后自动合并合并请求。`],
  [`Allow auto-merge`, `允许自动合并`],
  [`Waits for merge requirements to be met and then merges automatically.`, `等待合并要求得到满足后自动合并。`],
  [`After pull requests are merged, you can have head branches deleted automatically.`, `合并请求合并后，您可以使头部分支自动删除。`],
  [`Automatically delete head branches`, `自动删除头部分支`],
  [`Deleted branches will still be able to be restored.`, `已删除的分支仍然可以恢复。`],
  [`Require contributors to sign off on web-based commits`, `要求贡献者对基于网页的提交进行签署 (Sign-off)`],
  [`Enabling this setting will require contributors to sign off on commits made through GitHub’s web interface. Signing off is a way for contributors to affirm that their commit complies with the repository's terms, commonly the Developer Certificate of Origin (DCO). Learn more about signing off on commits.`, `启用此设置将要求贡献者对通过 GitHub 网页界面进行的提交进行签署（Sign-off）。签署是贡献者确认其提交符合仓库条款（通常为开发者原创证书，即 DCO）的一种方式。了解更多关于签署提交的信息。`],
  [`Allow comments on individual commits`, `允许对单个提交发表评论`],
  [`Enabling this setting will allow anyone who can view this repository to add commit comments. Existing commit comments are not affected by this setting and will remain viewable, editable, and deletable.`, `启用此设置将允许任何可以查看此仓库的人添加提交评论。现有的提交评论不受此设置影响，仍可查看、编辑和删除。`],
  [`When creating source code archives, you can choose to include files stored using Git LFS in the archive.`, `创建源代码归档文件时，您可以选择在归档中包含使用 Git LFS 存储的文件。`],
  [`Include Git LFS objects in archives`, `在归档中包含 Git LFS 对象`],
  [`Git LFS usage in archives is billed at the same rate as usage with the client.`, `在归档中使用 Git LFS 的费用与同客户端使用费率相同。`],
  [`Pushes will be rejected if they attempt to update more than this. Learn more about this setting, and send us your feedback.`, `如果尝试更新的分支和标签数超过此限制，推送将被拒绝。了解有关此设置的更多信息，并向我们发送反馈。`],
  [`For security reasons, you cannot change the visibility of a fork.`, `由于安全原因，您无法更改复刻（Fork）仓库的可见性。`],
  [`Disable branch protection rules enforcement and APIs`, `禁用分支保护规则强制执行与 API`],
  [`Transfer this repository to another user or to an organization where you have the ability to create repositories.`, `将此仓库转移给其他用户，或转移到您有权创造仓库的组织。`],
  [`Leave fork network`, `退出复刻网络`],
  [`Unlink this repository from the fork network and make it standalone.`, `断开此仓库与复刻网络的连接，使其成为独立仓库。`],
  [`Wikis`, `Wiki`],
  [`Sponsorships`, `赞助`],
  [`Footer`, `页脚`],
  [`Footer navigation`, `页脚导航`],
  [`Welcome to the githubCN wiki!`, `欢迎来到 githubCN Wiki！`],
  [`Wikis provide a place in your repository to lay out the roadmap of your project, show the current status, and document software better, together.`, `Wiki 在您的仓库中提供了一个空间，用于规划项目路线图、展示当前状态，并共同更好地记录软件文档。`],
  [`Create the first page`, `创建第一个页面`],
  [`Create new page`, `创建新页面`],
  [`Write`, `编辑`],
  [`Preview`, `预览`],
  [`Link a project`, `关联项目`],
  [`Created by me`, `我创建的`],
  [`GitHub Copilot app`, `GitHub Copilot 应用`],
  [`Start sessions in a desktop experience with visual diff review and multi-session support.`, `在桌面端体验中启动会话，支持可视化差异评审和多会话支持。`],
  [`Download`, `下载`],
  [`Give feedback`, `提供反馈`],
  [`Active`, `进行中`],
  [`Completed`, `已完成`],
  [`New pull request`, `新建合并请求`],
  [`Welcome to pull requests!`, `欢迎使用合并请求！`],
  [`Pull requests help you collaborate on code with other people. As pull requests are created, they’ll appear here in a searchable and filterable list. To get started, you should create a pull request.`, `合并请求可帮助您与其他人协作编写代码。创建合并请求后，它们将显示在此处的自搜索和过滤列表中。要开始使用，您应该创建一个合并请求。`],
  [`create a pull request.`, `创建合并请求。`],
  [`ProTip!`, `小提示！`],
  [`Ears burning? Get`, `有人提到你？使用`],
  [`mentions with`, `来接收 @ 提及`],
  [`Findings`, `发现`],
  [`Malware`, `恶意软件`],
  [`Vulnerabilities`, `漏洞`],
  [`Secret scanning`, `机密扫描`],
  [`Security policy`, `安全策略`],
  [`Advisories`, `安全公告`],
  [`Set up a security policy`, `设置安全策略`],
  [`View security advisories`, `查看安全公告`],
  [`Enable vulnerability reporting`, `启用漏洞报告`],
  [`Enable Dependabot alerts`, `启用 Dependabot 警报`],
  [`Set up code scanning`, `设置代码扫描`],
  [`Pulse`, `脉络`],
  [`Network`, `网络`],
  [`Actions usage metrics`, `Actions 使用指标`],
  [`Actions performance metrics`, `Actions 性能指标`],
];

const regexData = [
  [/(\d+)\s+commits?\s+ahead\s+of/i, '领先 $1 个提交'],
  [/(\d+)\s+commits?\s+behind/i, '落后 $1 个提交'],
  [/(\d+)\s+seconds?\s+ago/i, '$1 秒前'],
  [/(\d+)\s+minutes?\s+ago/i, '$1 分钟前'],
  [/(\d+)\s+hours?\s+ago/i, '$1 小时前'],
  [/(\d+)\s+days?\s+ago/i, '$1 天前'],
  [/(\d+)\s+weeks?\s+ago/i, '$1 周前'],
  [/(\d+)\s+months?\s+ago/i, '$1 个月前'],
  [/(\d+)\s+years?\s+ago/i, '$1 年前'],
  [/(\d+)\s+Branch/i, '$1 个分支'],
  [/(\d+)\s+Branches/i, '$1 个分支'],
  [/(\d+)\s+tags?/i, '$1 个标签'],
  [/(\d+)\s+stars?/i, '$1 颗星'],
  [/(\d+)\s+watching/i, '$1 人关注'],
  [/(\d+)\s+forks?/i, '$1 次复刻'],
];

const MutationObserverConfig = {
  childList: true,
  subtree: true,
  attributeFilter: ["data-label"],
  characterData: true,
};

const observer = new MutationObserver(function (mutations) {
  const treeWalker = document.createTreeWalker(
    document.body,
    NodeFilter.SHOW_ALL,
    {
      acceptNode: function (node) {
        if (
          node.nodeType === 3 ||
          (node.hasAttribute &&
            (node.hasAttribute("data-label") ||
              node.hasAttribute("placeholder") ||
              node.hasAttribute("value")))
        ) {
          return NodeFilter.FILTER_ACCEPT;
        } else {
          return NodeFilter.FILTER_SKIP;
        }
      },
    },
    false
  );
  let dataMap = new Map();
  allData.forEach(([key, val]) => {
    if (key && !dataMap.has(key)) {
      dataMap.set(key, val);
    }
  });
  let currentNode = treeWalker.currentNode;
  while (currentNode) {
    if (currentNode.nodeType === 3) {
      let key1 = currentNode.textContent
        .replace(/^\s*|\s*$/g, "")
        .replace(/\s+/g, " ");
      if (dataMap.has(key1)) {
        currentNode.textContent = dataMap.get(key1);
      } else {
        for (let [rx, repl] of regexData) {
          if (rx.test(key1)) {
            currentNode.textContent = key1.replace(rx, repl);
            break;
          }
        }
      }
    } else {
      let key2 = currentNode.getAttribute("data-label");
      if (key2 && dataMap.has(key2))
        currentNode.setAttribute("data-label", dataMap.get(key2));
      let key3 = currentNode.getAttribute("placeholder") || "";
      if ((key3 = key3.trim())) {
        if (dataMap.has(key3))
          currentNode.setAttribute("placeholder", dataMap.get(key3));
      }
      let key4 = currentNode.getAttribute("value");
      if (currentNode.tagName == "INPUT" && dataMap.has(key4)) {
        currentNode.setAttribute("value", dataMap.get(key4));
        let key5 = currentNode.getAttribute("data-signin-label");
        let key6 = currentNode.getAttribute("data-disable-with");
        currentNode.setAttribute("data-signin-label", dataMap.get(key5));
        currentNode.setAttribute("data-disable-with", dataMap.get(key6));
      }
    }
    currentNode = treeWalker.nextNode();
  }
});

observer.observe(document.body, MutationObserverConfig);
